### ISSUE TITLE
Add other resolutions

### ISSUE THREAD

**Issue by bjgood** [mathsgrinds/USTVNOWSHARPE#1]
Hi Stephen,
First of all, my wife has a niece who married an Irish lad and lives over there as well. His name is Markus (I can't think of his last name right now). BTW, I'm from the US.

I have a request. Can you add other resolution choices besides SD (which shows up as 720 on my TV screen) or HD? I'd like to see a lower resolution setting. USTVNow has a low setting.

A nice and simple addon. I like it.

Best regards,
Bob

**Comment by mathsgrinds** [comment]
Hi Bob. Thanks for your email J
I can try to add in, thanks for your input, the latest version has a quality button but I’m not sure if it works right

Thanks again.

**Comment by mathsgrinds** [comment]
All good with the update? I don't really know how the quality settings work. I don't see any change in the url when I change quality settings. I had a stab at it.
